openapi: 3.0.0
info:
  title: MERN stack API class
  version: 1.0.0
paths:
  /users:
    get:
      summary: Retrieve a list of users
      responses:
        "200":
          description: A list of users
